name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Publish .NET Core Project
        run: dotnet publish WavesSpy.sln -c Release --output release --nologo
        
      # changes the base-tag in index.html from '/' to 'waves-spy' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to waves-spy
        run: sed -i 's/<base href="\/" \/>/<base href="\/waves-spy\/" \/>/g' release/wwwroot/index.html
        
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Uploading files to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: release/wwwroot
